<?php
/**
 * @category    Kirchbergerknorr
 * @package     Kirchbergerknorr_ProductRedirect
 * @author      Oliver Sokola <oliver.sokola@kirchbergerknorr.de>
 * @copyright   Copyright (c) 2015 kirchbergerknorr GmbH (http://www.kirchbergerknorr.de)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @block: Kirchbergerknorr_ProductRedirect_Block_Productredirect
 */


$name = $this->getRedirectProductName();
$description = $this->getRedirectProductDesc();
$categoryIds = $this->getRedirectProductCategoryIds();
$helper = Mage::helper('productredirect/data');
?>

<div class="redirectContainer">
    <h1>
        <?php echo $this->__('We are sorry')?>!
    </h1>
    <div>
        <h2><?php echo $this->__("Our product \"%s\" is no longer available.", "<strong>".$name."</strong>");?></h2>
        <?php if(is_array($categoryIds) && $categoryIds[0] !== 0 && $helper->DoCategoriesExist($categoryIds)):?>
            <div class="suggestions">
                <p><?php echo $this->__("You might be interested in these categories:") ?></p>
                <ul>
                    <?php foreach($categoryIds as $categoryId):?>
                        <?php
                        $catUrl = $helper->getCategoryUrl($categoryId);
                        $catName = $helper->getCategoryName($categoryId);
                        ?>
                        <?php if(!empty($catUrl) && !empty($catName)): ?>
                            <li>
                                <a href="<?php echo $catUrl?>">
                                    <?php echo $catName?>
                                </a>
                            </li>
                        <?php endif ?>
                    <?php endforeach ?>
                </ul>
            </div>
        <?php endif;?>
        <br>
    </div>
</div>